# Generated by Django 3.1 on 2020-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_message_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(1, 'Submitted to the newspaper'), (2, 'resolved'), (3, 'no action taken'), (4, 'open')], default=4, max_length=100),
        ),
    ]
