# Generated by Django 3.1 on 2020-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Submitted to the newspaper'), (2, 'resolved'), (3, 'no action taken'), (4, 'open')], default=4, max_length=100),
        ),
    ]
