# Generated by Django 3.1 on 2020-12-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201219_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user_id', 'issue_id')},
        ),
    ]
